-- Active: 1736032503943@@dpg-ctsqup3v2p9s738doedg-a.oregon-postgres.render.com@5432@basedatosfullstack@public

--CREACION DE UNA BASE DE DATOS EN SQL POSTGRESQL
--CREATE DATABASE COLEGIO;

--creacion de tablas usuario
-- nombre atributo o campo; tipos datos / propiedades

CREATE TABLE USUARIO(
  ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(50),
  CORREO VARCHAR(100) NOT NULL UNIQUE,
  CONTRASENA VARCHAR(10) DEFAULT 123,
  FECHA_REGISTRO DATE
);


CREATE TABLE CLIENTES(
ID SERIAL PRIMARY KEY,
NOMBRE VARCHAR(255),
APELLIDO VARCHAR(255),
CORREO VARCHAR(255)
);


ALTER TABLE CLIENTES
--ADD
--ADD COLUMN EDAD INTEGER
--RENAME
--RENAME COLUMN EDAD TO YEAR
--DROP
DROP COLUMN YEAR

DROP TABLE CLIENTES;
DROP TABLE PRUEBA;

