-- Active: 1736032503943@@dpg-ctsqup3v2p9s738doedg-a.oregon-postgres.render.com@5432@basedatosfullstack@public
-- RELACION DE UNO A MUCHOS, UN AUTOR PUEDE ESCRIBIR MUCHOS LIBROS Y MUCHOS LIBROS PERTENECEN A UN AUTOR
CREATE TABLE AUTOR(
ID SERIAL PRIMARY KEY,
NOMBRE VARCHAR(255)
);

CREATE TABLE LIBRO(
ID SERIAL PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL,
ID_AUTOR INTEGER NOT NULL,
FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID)
);

--RELACION DE MUCHOS A MUCHOS, UN LIBRO PUEDE TERN VARIOS GENEROS, Y UN GENERO PUEDE APLICARSE A VARIOS LIBROS

CREATE TABLE GENERO(
ID SERIAL PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL
);

CREATE TABLE LIBRO_GENERO(
ID_LIBRO INTEGER NOT NULL,
ID_GENERO INTEGER NOT NULL,
PRIMARY KEY (ID_LIBRO, ID_GENERO),
FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID),
FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID)
);

--UNO A UNO

CREATE TABLE DETALLE_LIBRO(
ID SERIAL PRIMARY KEY,
ID_LIBRO INTEGER NOT NULL UNIQUE,
RESUMEN TEXT,
PAGINAS INTEGER,
FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);


