-- Active: 1736032503943@@dpg-ctsqup3v2p9s738doedg-a.oregon-postgres.render.com@5432@basedatosfullstack@public
--JOINS
SELECT * 
FROM LIBRO

SELECT * FROM LIBRO_GENERO

SELECT *
FROM GENERO

--LISTAR LOS GENEROS DE LOS LIBROS
SELECT LIBRO.NOMBRE , GENERO.NOMBRE
FROM LIBRO,
     GENERO,
     LIBRO_GENERO
WHERE LIBRO.ID = LIBRO_GENERO.ID_LIBRO AND
      GENERO.ID = LIBRO_GENERO.ID_GENERO

SELECT LIBRO.NOMBRE , GENERO.NOMBRE
FROM LIBRO
INNER JOIN LIBRO_GENERO ON LIBRO.ID = LIBRO_GENERO.ID_LIBRO
INNER JOIN GENERO ON GENERO.ID = LIBRO_GENERO.ID_GENERO

--LISTAR TODOS LOS AUTORES Y REVISAR SI TIENEN LIBROS

SELECT *
FROM AUTOR
LEFT JOIN LIBRO ON ID_AUTOR = LIBRO.ID_AUTOR

-- LISTAR TODOS LOS LIBROS Y REVISAR  SI EXISTEN LOS NOMBRE DE SUS AUTORES

SELECT *
FROM AUTOR
RIGHT JOIN LIBRO ON ID_AUTOR = LIBRO.ID_AUTOR

--CONSULTAR TODOS LOS LIBROS INCLUISO SINO  ESTAN RELACIONADOS
SELECT * 
FROM AUTOR
FULL OUTER JOIN LIBRO ON AUTOR.ID = LIBRO.ID_AUTOR